### PR TITLE
Updates per request (take 2)

### PR DESCRIPTION
**Pull request by afgaron**
I added an additional error catching check to handle the issue you brought up at AAS. The code now handle that like other external errors (waits and tries again).
I also went through the SQL calls to SDSS. I consolidated 3 of them, so now there are only 2: 1 to determine the positional match (and colors) and 1 to pull all the other data (redshift, emission lines, etc) based on the positional match's ID.

### CODE REVIEW

**Comment by willettk** [comment]
Thanks, @afgaron. I'm running a test with a fresh version of the catalog now on the UMN servers. If it passes, we'll merge in the changes.

**Comment by willettk** [comment]
Rats. It ran for several days, and then this was thrown: 

```
45882
45883
45884
45885
45886
45887
45888
45889
45890
Traceback (most recent call last):
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 425, in <module>
    output = str(RGZcatalog()) + ' entries added.'
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 86, in RGZcatalog
    for subject in subjects.find().batch_size(10):
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/pymongo/cursor.py", line 919, in _refresh
    self.__id))
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/pymongo/cursor.py", line 839, in __send_message
    codec_options=self.__codec_options)
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/pymongo/helpers.py", line 110, in _unpack_response
    cursor_id)
pymongo.errors.CursorNotFound: cursor id '56594071498' not valid at server
Outputting static catalog
0 entries written to CSV file ./rgz-analysis/csv/static_rgz_flat.csv
0 had errors writing data to file
Closing Python environments
Dumping Mongo files
2016-02-17T03:57:04.645-0600    writing radio.radio_classifications to rgz_mongo/radio/radio_classifications.bson
2016-02-17T03:57:04.650-0600    writing radio.consensus to rgz_mongo/radio/consensus.bson
2016-02-17T03:57:04.652-0600    writing radio.radio_users to rgz_mongo/radio/radio_users.bson
2016-02-17T03:57:04.657-0600    writing radio.system.indexes to rgz_mongo/radio/system.indexes.bson
2016-02-17T03:57:04.658-0600    writing radio.radio_groups to rgz_mongo/radio/radio_groups.bson
2016-02-17T03:57:04.662-0600    writing radio.radio_subjects to rgz_mongo/radio/radio_subjects.bson
2016-02-17T03:57:04.663-0600    writing radio.catalog to rgz_mongo/radio/catalog.bson
2016-02-17T03:57:04.972-0600    writing radio.radio_groups metadata to rgz_mongo/radio/radio_groups.metadata.json
2016-02-17T03:57:05.051-0600    done dumping radio.radio_groups (2 documents)
2016-02-17T03:57:06.151-0600    writing radio.consensus metadata to rgz_mongo/radio/consensus.metadata.json
2016-02-17T03:57:06.152-0600    done dumping radio.consensus (98062 documents)
2016-02-17T03:57:06.658-0600    writing radio.catalog metadata to rgz_mongo/radio/catalog.metadata.json
2016-02-17T03:57:06.659-0600    done dumping radio.catalog (45890 documents)
2016-02-17T03:57:06.693-0600    writing radio.radio_users metadata to rgz_mongo/radio/radio_users.metadata.json
2016-02-17T03:57:06.717-0600    done dumping radio.radio_users (16098 documents)
2016-02-17T03:57:07.629-0600    [........................]  radio.radio_classifications  44843/1614065   (2.8%)
2016-02-17T03:57:07.629-0600    [#######.................]         radio.radio_subjects   58228/177461  (32.8%)
2016-02-17T03:57:07.629-0600
2016-02-17T03:57:10.102-0600    writing radio.radio_subjects metadata to rgz_mongo/radio/radio_subjects.metadata.json
2016-02-17T03:57:10.103-0600    done dumping radio.radio_subjects (177461 documents)
2016-02-17T03:57:10.629-0600    [##......................]  radio.radio_classifications  146154/1614065  (9.1%)
2016-02-17T03:57:13.629-0600    [####....................]  radio.radio_classifications  311468/1614065  (19.3%)
2016-02-17T03:57:16.630-0600    [######..................]  radio.radio_classifications  453329/1614065  (28.1%)
2016-02-17T03:57:19.629-0600    [#########...............]  radio.radio_classifications  610410/1614065  (37.8%)
2016-02-17T03:57:22.629-0600    [###########.............]  radio.radio_classifications  780592/1614065  (48.4%)
2016-02-17T03:57:25.629-0600    [##############..........]  radio.radio_classifications  949861/1614065  (58.8%)
2016-02-17T03:57:28.629-0600    [################........]  radio.radio_classifications  1137308/1614065  (70.5%)
2016-02-17T03:57:31.629-0600    [###################.....]  radio.radio_classifications  1300546/1614065  (80.6%)
2016-02-17T03:57:34.629-0600    [#####################...]  radio.radio_classifications  1460035/1614065  (90.5%)
2016-02-17T03:57:37.326-0600    writing radio.radio_classifications metadata to rgz_mongo/radio/radio_classifications.metadata.json
2016-02-17T03:57:37.327-0600    done dumping radio.radio_classifications (1614065 documents)
Killing MongoDB
```

I thought that was supposed to be fixed by setting a lower batch size. Any more ideas, @afgaron?

**Comment by afgaron** [comment]
I guess the batch size just isn't small enough. I never had issues when I tested it with batch size of 30, so I'm surprised this happened with one of 10. As a last resort, we can try setting the time-out off and manually close the cursor at the end.

**Comment by willettk** [comment]
Yeah. Quite a lot of StackOverflow subjects seem to suggest against that,
but I'm not sure what else to do.

Can you explain to me what `batch_size` actually means in this case? How
does that set a specific time-out length for the server?

**Comment by afgaron** [comment]
What you're reading on SO and in the docs is the extent of my knowledge. As far as I understand it, a number of documents equal to the batch size is returned on the find command. Once they're all processed, the next batch is returned. After 10 minutes of no activity, the connection closes, so we need to process the full batch within the 10 minutes. Each time a new batch is called, the timer resets.

**Comment by willettk** [comment]
OK. So we have at least a couple of options:

- manually opening and closing the cursor
- setting the batch size even lower (say to 1)
- reiterating again on the error handling for the CursorNotFound event, and
logging it directly so we can clean it up later

The last option seems preferable to me, but I'd like to hear what you
think.

**Comment by afgaron** [comment]
If we manually control the cursor, we'll still need error handing to close it in case something else hiccups. I'm not sure what'll happen if we leave the cursor open, but it can't be good. I feel like lowering the batch size won't help in the cases where it's not working right now and it'll add unnecessary overhead to the vast majority of cases. As for error handling, it should be easy to make a catch that checks for this error and just redoes the for loop. If we just do that, though, it'll have to find where it left off using the current code; if I remember right, that takes on order of minutes? So not too bad.

-Avery Garon

**Comment by willettk** [comment]
OK. If you think you can do it, do you want to try putting in the error
handling case? If everything exists properly, I think that should fix it.

**Comment by afgaron** [comment]
I'm working on that right now and also just making the code more clear, and I want to clarify something with your determine_paths assignment. If the paths aren't present, shouldn't the code just cleanly abort? Right now you return None and that leads to unhandled errors later.

**Comment by willettk** [comment]
Yep - bad coding on my part. If you can fix that as well, please do.

**Comment by afgaron** [comment]
I couldn't figure out a great way to do it, so I just put the call to RGZcatalog() inside a while true loop. When the cursor times out, the whole thing stops, waits 10 seconds, and runs from the top. This is basically the worst case scenario but automated. If there's something actually wrong with the connection, I couldn't figure out a way to check so it'll just keep trying until manually terminated.

**Comment by willettk** [comment]
OK, thanks. Is that in the current PR so we can test it?

**Comment by afgaron** [comment]
Yes it is.

**Comment by willettk** [comment]
It worked on the short updated version; I'm trying again on remaking the full catalog. 

In the meantime, can you fix the small string error here?

https://github.com/afgaron/rgz-analysis/blob/master/RGZcatalogCode/RGZcatalog.py#L213

**Comment by willettk** [comment]
Still had another error. 

```
50346
50347
Traceback (most recent call last):
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 211, in <module>
    except pymongo.errors.CursorNotFound as c:
NameError: name 'pymongo' is not defined
Outputting static catalog
0 entries written to CSV file ./rgz-analysis/csv/static_rgz_flat.csv
0 had errors writing data to file
Closing Python environments
Dumping Mongo files
```

This one's simple - I think it's just not imported at the top. Can you correct it in your repo and we'll try again?

**Comment by afgaron** [comment]
I feel dumb. I know I did that, but must have saved the wrong version. Fixed.

**Comment by willettk** [comment]
Missing another import (see https://github.com/afgaron/rgz-analysis/blob/master/RGZcatalogCode/processing.py#L33). Threw the error below:

```
51489
51490
Traceback (most recent call last):
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 207, in <module>
    output = '%i entries added.' % RGZcatalog()
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 129, in RGZcatalog
    sdss_match = p.getSDSS(entry)
  File "/data/tabernacle/larry/RGZdata/rgz-analysis/RGZcatalogCode/processing.py", line 112, in getSDSS
    df = SDSS_select(query)
  File "/data/tabernacle/larry/RGZdata/rgz-analysis/RGZcatalogCode/processing.py", line 97, in SDSS_select
    time.sleep(10)
NameError: global name 'time' is not defined
```

**Comment by afgaron** [comment]
Fixed. Can you check the log to see if the cursor error has been encountered yet?

**Comment by willettk** [comment]
It happened a few times the last time it ran, yes. The relevant section of the log looks like this: 

```
2016-02-23 14:12:38: Processing subject field ARG0001wzg
1664592 2016-02-23 14:12:38: Processing consensus object A within subject field ARG0001wzg
1664593 2016-02-23 14:12:38: IR counterpart found
1664594 2016-02-23 14:12:39: Starting new HTTP connection (1): irsa.ipac.caltech.edu
1664595 2016-02-23 14:13:39: Query timed out, time elapsed 60s
1664596 Traceback (most recent call last):
1664597   File "/data/tabernacle/larry/RGZdata/rgz-analysis/RGZcatalogCode/processing.py", line 26, in getWISE
1664598     table = Irsa.query_region(ir_pos, catalog='wise_allwise_p3as_psd', radius=3*u.arcsec)
1664599   File "/home/phys/willett/veastropy/lib/python2.7/site-packages/astroquery/irsa/core.py", line 167, in query_region
1664600     get_query_payload=get_query_payload)
1664601   File "/home/phys/willett/veastropy/lib/python2.7/site-packages/astroquery/irsa/core.py", line 229, in query_region_async
1664602     Irsa.TIMEOUT, request_type='GET')
1664603   File "/home/phys/willett/veastropy/lib/python2.7/site-packages/astroquery/utils/commons.py", line 99, in send_request
1664604     format(time=timeout))
1664605 TimeoutError: Query timed out, time elapsed 60s
1664606 2016-02-24 21:16:41: Catalog run from command line
1664607 2016-02-24 21:16:41: Connecting to MongoDB
1664608 2016-02-24 21:16:41: [Errno 2] No such file or directory: '/data/tabernacle/larry/RGZdata/rgz-analysis/first_fits.txt'
```

**Comment by afgaron** [comment]
Oh, so did it not successfully handle it then? Looks like you manually re-ran.

**Comment by willettk** [comment]
A couple times, yes. As I said: the goal is to have it run, start to finish, on a fresh install of the catalog. We'll get it sooner or later. 

It threw a new error last night: 

```
2016-03-02 10:00:11: Entry 75192 added to catalog
2016-03-02 10:00:11: Processing subject field ARG000318h
2016-03-02 10:00:11: Processing subject field ARG000318g
2016-03-02 10:00:11: Processing subject field ARG0003185
2016-03-02 10:00:11: Processing consensus object A within subject field ARG0003185
2016-03-02 10:00:11: IR counterpart found
2016-03-02 10:00:11: Starting new HTTP connection (1): irsa.ipac.caltech.edu
2016-03-02 10:00:12: "GET /cgi-bin/Gator/nph-query?radunits=arcsec&outfmt=3&objstr=234.26221803+%2B10.5365699642&catalog=wise_allwise_p3as_psd&radius=3.0&spatial=Cone&outrows=500 HTTP/1.1" 200 None
2016-03-02 10:00:13: AllWISE match found
2016-03-02 10:00:14: No SDSS match found
2016-03-02 10:00:14: Radio data added
2016-03-02 10:00:14: Entry 75193 added to catalog
2016-03-02 10:00:14: Processing subject field ARG000318x
2016-03-02 10:00:14: Processing consensus object A within subject field ARG000318x
2016-03-02 10:00:14: IR counterpart found
2016-03-02 10:00:14: Starting new HTTP connection (1): irsa.ipac.caltech.edu
2016-03-02 10:00:15: "GET /cgi-bin/Gator/nph-query?radunits=arcsec&outfmt=3&objstr=237.255722429+%2B10.5315077589&catalog=wise_allwise_p3as_psd&radius=3.0&spatial=Cone&outrows=500 HTTP/1.1" 200 None
2016-03-02 10:00:15: Failed to parse IRSA votable! The raw response can be found in self.response, and the error in self.table_parse_error.
Traceback (most recent call last):
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 207, in <module>
    output = '%i entries added.' % RGZcatalog()
  File "rgz-analysis/RGZcatalogCode/RGZcatalog.py", line 125, in RGZcatalog
    wise_match = p.getWISE(entry)
  File "/data/tabernacle/larry/RGZdata/rgz-analysis/RGZcatalogCode/processing.py", line 26, in getWISE
    table = Irsa.query_region(ir_pos, catalog='wise_allwise_p3as_psd', radius=3*u.arcsec)
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/astroquery/irsa/core.py", line 170, in query_region
    return self._parse_result(response, verbose=verbose)
  File "/home/phys/willett/veastropy/lib/python2.7/site-packages/astroquery/irsa/core.py", line 360, in _parse_result
    raise TableParseError("Failed to parse IRSA votable! The raw response can be found "
TableParseError: Failed to parse IRSA votable! The raw response can be found in self.response, and the error in self.table_parse_error.
```

This one's new to me, but looks like a problem with the format of the IRSA object. Could you:

1. experiment with that particular source and see if the problem is recreated? 
2. set up an additional error handling for TableParseErrors? As with the timeouts, I think we should skip the WISE search and note that it happened, but proceed with the SDSS match and then the next entry in the catalog.

**Comment by afgaron** [comment]
I wasn't able to reproduce it. I couldn't find what actually triggers this one, so I just put it with the other error-handling for now.

**Comment by willettk** [comment]
Thanks, @afgaron. Can I try running it again?

**Comment by afgaron** [comment]
Go ahead.

**Comment by willettk** [comment]
Success, I think!

```
98061
98062
Time taken: 109756.112181
22869 entries added.
Outputting static catalog
0 entries written to CSV file ./rgz-analysis/csv/static_rgz_flat.csv
0 had errors writing data to file
Closing Python environments
Dumping Mongo files
2016-03-05T06:20:28.796-0600    writing radio.radio_classifications to rgz_mongo/radio/radio_classifications.bson
2016-03-05T06:20:28.813-0600    writing radio.catalog to rgz_mongo/radio/catalog.bson
2016-03-05T06:20:28.880-0600    writing radio.consensus to rgz_mongo/radio/consensus.bson
2016-03-05T06:20:28.882-0600    writing radio.radio_subjects to rgz_mongo/radio/radio_subjects.bson
2016-03-05T06:20:28.883-0600    writing radio.radio_groups to rgz_mongo/radio/radio_groups.bson
2016-03-05T06:20:28.908-0600    writing radio.radio_users to rgz_mongo/radio/radio_users.bson
2016-03-05T06:20:28.909-0600    writing radio.system.indexes to rgz_mongo/radio/system.indexes.bson
2016-03-05T06:20:28.934-0600    writing radio.radio_groups metadata to rgz_mongo/radio/radio_groups.metadata.json
2016-03-05T06:20:28.935-0600    done dumping radio.radio_groups (2 documents)
2016-03-05T06:20:29.671-0600    writing radio.catalog metadata to rgz_mongo/radio/catalog.metadata.json
2016-03-05T06:20:29.672-0600    done dumping radio.catalog (98062 documents)
2016-03-05T06:20:30.235-0600    writing radio.consensus metadata to rgz_mongo/radio/consensus.metadata.json
2016-03-05T06:20:30.236-0600    done dumping radio.consensus (105950 documents)
2016-03-05T06:20:31.773-0600    [........................]  radio.radio_classifications  55603/1640377   (3.4%)
2016-03-05T06:20:31.773-0600    [#######.................]         radio.radio_subjects   58193/177461  (32.8%)
2016-03-05T06:20:31.773-0600    [........................]            radio.radio_users      101/16098   (0.6%)
2016-03-05T06:20:31.773-0600
2016-03-05T06:20:32.997-0600    writing radio.radio_users metadata to rgz_mongo/radio/radio_users.metadata.json
2016-03-05T06:20:32.999-0600    done dumping radio.radio_users (16098 documents)
2016-03-05T06:20:34.773-0600    [#.......................]  radio.radio_classifications  93199/1640377   (5.7%)
2016-03-05T06:20:34.773-0600    [##############..........]         radio.radio_subjects  105862/177461  (59.7%)
2016-03-05T06:20:34.773-0600
2016-03-05T06:20:35.876-0600    writing radio.radio_subjects metadata to rgz_mongo/radio/radio_subjects.metadata.json
2016-03-05T06:20:35.877-0600    done dumping radio.radio_subjects (177461 documents)
2016-03-05T06:20:37.773-0600    [##......................]  radio.radio_classifications  198029/1640377  (12.1%)
2016-03-05T06:20:40.773-0600    [#####...................]  radio.radio_classifications  403787/1640377  (24.6%)
2016-03-05T06:20:43.773-0600    [########................]  radio.radio_classifications  585635/1640377  (35.7%)
2016-03-05T06:20:46.773-0600    [###########.............]  radio.radio_classifications  760258/1640377  (46.3%)
2016-03-05T06:20:49.773-0600    [#############...........]  radio.radio_classifications  928378/1640377  (56.6%)
2016-03-05T06:20:52.773-0600    [################........]  radio.radio_classifications  1129614/1640377  (68.9%)
2016-03-05T06:20:55.773-0600    [###################.....]  radio.radio_classifications  1303928/1640377  (79.5%)
2016-03-05T06:20:58.773-0600    [#####################...]  radio.radio_classifications  1466253/1640377  (89.4%)
2016-03-05T06:21:01.773-0600    [######################..]  radio.radio_classifications  1534408/1640377  (93.5%)
2016-03-05T06:21:04.773-0600    [#######################.]  radio.radio_classifications  1589899/1640377  (96.9%)
2016-03-05T06:21:07.773-0600    [#######################.]  radio.radio_classifications  1633661/1640377  (99.6%)
2016-03-05T06:21:08.159-0600    writing radio.radio_classifications metadata to rgz_mongo/radio/radio_classifications.metadata.json
2016-03-05T06:21:08.160-0600    done dumping radio.radio_classifications (1640377 documents)
Killing MongoDB
```

**Comment by willettk** [comment]
Hopefully SDSS and IRSA aren't mad at us for constantly querying their database over the past couple of weeks. Really wish they had proper API keys.

**Comment by afgaron** [comment]
Yay. You're certain there's no better way to query their databases? Having to go through the web interfaces is by far the slowest part. (Although I guess even the radio data is being read from the RGZ website.)

**Comment by willettk** [comment]
No, I'm not certain - but haven't really looked into it yet, at least from the multi-wavelength sides. SDSS is supposedly moving to a new interface sometime this year that should support that, but the launch date got delayed and seems to be "undetermined" right now. 

The radio data isn't being read from the website, though - that's a static dump that we store as a local database, right?

**Comment by afgaron** [comment]
No? Not one of which I was aware. Each subject has a link to a json (e.g. http://radio.galaxyzoo.org/subjects/contours/52af7d53eb9a9b05ef000001.json), and I've been loading the contour data from there.

**Pull request merged**
