### PR TITLE
Revisions for run_sample with weighting.

### PR DESCRIPTION
**Pull request by willettk**

### CODE REVIEW

**Comment by ivyw** [comment]
so how did the double weighting go?

**Comment by willettk** [comment]
Matching against individual objects now, but here's a first look:

weights_histogram

So, what does this show?

1. Total consensus votes per subject goes up by weighting the votes, as expected; scales roughly as factor of _w_.
2. The consensus fraction goes up slightly for increasing weights. At the 75% level we've been using, the fraction of galaxies designated as "reliable" would increase from ~60% to 70% of the sample. So they're more confident.
3. The number of radio components per subjects doesn't appreciably change. Weighted votes are very slightly more likely to find more radio components in a particular image.

**Comment by ivyw** [comment]
Oh this is great! An increase from 60% to 70 % reliable gives us ~16% more sources to play with so this is definitely useful! Thank you very much Kyle for checking this.  I guess our keen users are very interested in finding Giant Radio Galaxies so they may be a little biased in that direction.  When you say "doesn't appreciably change", what is it statistically?

**Comment by willettk** [comment]
I'm being lazy about the numbers, you're right. It was based on the n_components = 1 bin in the leftmost grid; there's a 1.1% difference (76.7% to 77.8%) between w=1 and w=10.

**Comment by ivyw** [comment]
Cool. Thanks heaps Kyle. If I am understanding this correctly, 76.7% and 77.8% are the percentage of votes that have reached a 0.75 consensus fraction that the radio galaxy is an n=1 source.  Sorry to be such a pain but have you checked that n_components=2  and =3 has a similarly small increase? I'd have assumed that the n_comp=1 should remain mostly unchanged and the changes are more likely to occur in subjects with many (n>2) radio sources....

**Pull request merged**
